build:
    title:
    input-folder: src
    output-folder: build
    related-title: See Also   
publish:
    url: https://success.outsystems.com/
    root_path: Documentation/
    toc_url: https://success.outsystems.com/
    toc_root_path: Documentation/
    skip_toc_publish: False
    skip_edit_links: True
reference:
    assemble-folder: 
        - src/ref/lang/auto
        - src/ref/apis/auto
checktoc:
    url: https://success.outsystems.com/
    root_path: ""
    mindtouch-toc-path: Documentation/
    auto-toc-path: Documentation/Unlisted/Technical_Communication/Wiki_Tree_next
