name: Validate Frontmatter

on:
  push:
    branches:
    - master
    - main
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  frontmatter-json-schema-validator:
    name: Validate Frontmatter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Validate Frontmatter
        uses: mheap/frontmatter-json-schema-action@main
        with:
          paths: "src/**/*.md"
          schema_path:  ./.github/workflows/frontmatter.json
